replicaCount: 3

image:
  hub: docker.io
  repository: mhristov/internal-service
  tag: "latest"
  pullPolicy: IfNotPresent

prod: true
env:
  LOG_LEVEL: "debug"
  FEATURE_FLAG: "enabled"
  CUSTOM_MESSAGE: "Hello from Prod!"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

service:
  type: ClusterIP
  port: 8080

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
