---
# Source: internal-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: internal-service
  labels:
    app: internal-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: internal-service
---
# Source: internal-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-service
  labels:
    app: internal-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: internal-service
  template:
    metadata:
      labels:
        app: internal-service
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: internal-service
          image: "docker.io/mhristov/internal-service:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PROD
              value: "false"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: internal-service
---
# Source: internal-service/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: internal-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: internal-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: internal-service/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "internal-service-test-connection"
  labels:
    helm.sh/chart: internal-service-0.1.0
    app.kubernetes.io/name: internal-service
    app.kubernetes.io/instance: internal-service
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['internal-service:8080']
  restartPolicy: Never
