# Replica count (default 3)
replicaCount: 3

# Image configuration
image:
  hub: docker.io
  repository: mhristov/internal-service
  tag: latest
  pullPolicy: IfNotPresent

# Environment
prod: false
env: {} # extra environment variables

# Resources
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Service
service:
  type: ClusterIP
  port: 8080

# Security context (best practices)
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
