apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-service
spec:
  template:
    spec:
      containers:
        - name: internal-service
          env:
            - name: PROD
              value: "false"
